apiVersion: batch/v1
kind: Job
metadata:
  name: testcase2-job
spec:
  template:
    spec:
      containers:
      - name: testcase2-container
        image: johnsonfight/tc_2_changebiosbootorder:latest
        # args: ["-ip", "192.168.0.120", "-u", "root", "-p", "password"]
        args: ["--script-examples"]
      restartPolicy: Never
  backoffLimit: 4